[package]
name = "r-snes"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "common",
    "ppu",
    "cpu",
    "apu",
    "cpu/instr_metalang_procmacro",
    "bus",
]

[dependencies]
minifb = "0.28"
eframe = "0.28"
egui = "0.28"
rfd = "0.14" # for file dialogs
