[package]
name = "bus"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common"}
duplicate = "2.0.0"
strum = "0.27.2"
strum_macros = "0.27.2"

[dev-dependencies]
tempfile = "3.23.0"

